[package]
name = "mdbook-gh-issue-preview"
version = "0.1.0"
edition = "2024"

[dependencies]
mdbook = "0.4.52"
regex = "1.12.2"
reqwest = { version = "0.12.28", features = ["blocking", "json"] }
serde = "1.0.228"
serde_json = "1.0.148"
